// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTManagerInterface is a mock of JWTManagerInterface interface.
type MockJWTManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerInterfaceMockRecorder
}

// MockJWTManagerInterfaceMockRecorder is the mock recorder for MockJWTManagerInterface.
type MockJWTManagerInterfaceMockRecorder struct {
	mock *MockJWTManagerInterface
}

// NewMockJWTManagerInterface creates a new mock instance.
func NewMockJWTManagerInterface(ctrl *gomock.Controller) *MockJWTManagerInterface {
	mock := &MockJWTManagerInterface{ctrl: ctrl}
	mock.recorder = &MockJWTManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManagerInterface) EXPECT() *MockJWTManagerInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJWTManagerInterface) GenerateToken(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJWTManagerInterfaceMockRecorder) GenerateToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJWTManagerInterface)(nil).GenerateToken), userID)
}

// ParseToken mocks base method.
func (m *MockJWTManagerInterface) ParseToken(tokenString string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", tokenString)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockJWTManagerInterfaceMockRecorder) ParseToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockJWTManagerInterface)(nil).ParseToken), tokenString)
}
